image: ruby:latest

pages:
  stage: deploy

  only:
  - main
  except:
    changes:
      - .dockerignore
      - .editorconfig
      - .gitattributes
      - .github/*
      - .gitignore
      - assets/aide_de_camp.py
      - assets/fonts/*.txt
      - Dockerfile
      - LICENSE
      - README.md

  script:
  - bundle install
  - bundle exec jekyll build --destination public
  # GitLab Pages only publish files in this folder

  artifacts:
    paths:
    - public
