image: ruby:alpine

before_script:
  - apk add --no-cache build-base gcc cmake nodejs
  - bundle install

test:
  stage: test
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
