image: ruby:alpine

pages:
  script:
    - apk add --no-cache build-base gcc cmake nodejs
    - bundle install
    - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
