title: Kinh nhật tụng
author: PTA
email: phantuananh@hotmail.com.vn
description: Vietnamese Mahayana Buddhism rituals in multiple languages
url: "https://phineas-pta.github.io"
baseurl: "/kinh_nhat_tung" # can be overidden with command line
github_username: phineas-pta

# Build settings
theme: null
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults: # make setup for all HTML, no need to do for each file
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default # html file in layout folder

collections_dir: texts
collections: # handle how entries are sorted in sidebar in webpage
  posts: # 1st collection is always `posts`
    output: false
  than-chu:
    collname: Các thần chú
    order: 1
    output: true
    sort_by: numb
  mo-dau:
    collname: Kệ mở đầu
    order: 2
    output: true
    sort_by: numb
  khai-kinh:
    collname: Kệ khai kinh
    order: 3
    output: true
    sort_by: numb
  chanh-kinh:
    collname: Chánh kinh
    order: 4
    output: true
    sort_by: numb
  thu-kinh:
    collname: Kệ thu kinh
    order: 5
    output: true
    sort_by: numb
  ket-thuc:
    collname: Kệ kết thúc
    order: 6
    output: true
    sort_by: numb

# do not change Liquid error mode, coz bug with sitemap

exclude:
  - .bundle/
  - .dockerignore
  - .editorconfig
  - .git/
  - .gitattributes
  - .github/
  - .gitignore
  - .gitlab-ci.yml
  - assets/aide_de_camp.py
  - assets/fonts/*.txt
  - Dockerfile
  - LICENSE
  - README.md
